---
title: "Descarga de capas geoespaciales"
format: 
  html:
    lang: es
    theme: cosmo
    toc: true
    toc-expand: 3
---


# Introducción
Este documento descarga las siguientes capas geoespaciales:

- Contorno de Costa Rica (se forma a partir de la unión de los polígonos de cantones).
- Áreas silvestres protegidas (ASP).


# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false
#| code-fold: show
#| code-summary: "Código"


# Paquetes
library(here)
library(dplyr)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leafem)
```


# Descarga de capas

## Contorno de Costa Rica

```{r}
#| label: descarga-costarica
#| eval: true


# Ruta a los archivos de salida
ARCHIVO_GPKG_COSTARICA <- here("datos", "finales", "costarica.gpkg")

# Direcciones WFS
WFS_BASE <- "https://geos.snitcr.go.cr/be/IGN_5_CO/wfs"
WFS_VERSION <- "1.0.0"
WFS_CAPA <- "IGN_5_CO:limitecantonal_5k"

# Solicitud WFS
solicitud_wfs <- sprintf(
  "request=GetFeature&service=WFS&version=%s&typename=%s&outputFormat=application/json",
  WFS_VERSION,
  URLencode(WFS_CAPA)
)

# Carga, reproyección, validación de geometrías y unión
capa_sf <-
  st_read(paste0(URLencode(WFS_BASE), "?", solicitud_wfs), quiet = TRUE) |>
  st_transform(4326) |>
  st_make_valid() |> 
  st_union()

# Escritura
capa_sf |>
  st_write(ARCHIVO_GPKG_COSTARICA, delete_dsn = TRUE, quiet = TRUE)
```


## Áreas Silvestres Protegidas (ASP)

```{r}
#| label: descarga-asp
#| eval: true


# Ruta a los archivos de salida
ARCHIVO_GPKG_ASP_1 <- here("datos", "finales", "areas-silvestres-protegidas.gpkg")
ARCHIVO_GPKG_ASP_2 <- here("programas", "geovisor", "areas-silvestres-protegidas.gpkg")

# Direcciones WFS
WFS_BASE <- "http://geos1pne.sirefor.go.cr/wfs"
WFS_VERSION <- "1.0.0"
WFS_CAPA <- "PNE:areas_silvestres_protegidas"

# Solicitud WFS
solicitud_wfs <- sprintf(
  "request=GetFeature&service=WFS&version=%s&typename=%s&outputFormat=application/json",
  WFS_VERSION,
  URLencode(WFS_CAPA)
)

# Carga, reproyección, validación de geometrías y unión
capa_sf <-
  st_read(paste0(URLencode(WFS_BASE), "?", solicitud_wfs), quiet = TRUE) |>
  st_transform(4326) |>
  st_make_valid()

# Escritura
capa_sf |>
  st_write(ARCHIVO_GPKG_ASP_1, delete_dsn = TRUE, quiet = TRUE)
capa_sf |>
  st_write(ARCHIVO_GPKG_ASP_2, delete_dsn = TRUE, quiet = TRUE)
```


## Áreas de Conservación

```{r}
#| label: descarga-ac
#| eval: true


# Ruta a los archivos de salida
ARCHIVO_GPKG_AC_1 <- here("datos", "finales", "areas-conservacion.gpkg")
ARCHIVO_GPKG_AC_2 <- here("programas", "geovisor", "areas-conservacion.gpkg")

# Direcciones WFS
WFS_BASE <- "http://geos1pne.sirefor.go.cr/wfs"
WFS_VERSION <- "1.0.0"
WFS_CAPA <- "PNE:areas_conservacion"

# Solicitud WFS
solicitud_wfs <- sprintf(
  "request=GetFeature&service=WFS&version=%s&typename=%s&outputFormat=application/json",
  WFS_VERSION,
  URLencode(WFS_CAPA)
)

# Carga, reproyección, validación de geometrías y unión
capa_sf <-
  st_read(paste0(URLencode(WFS_BASE), "?", solicitud_wfs), quiet = TRUE) |>
  st_transform(4326) |>
  st_make_valid()

# Escritura
capa_sf |>
  st_write(ARCHIVO_GPKG_AC_1, delete_dsn = TRUE, quiet = TRUE)
capa_sf |>
  st_write(ARCHIVO_GPKG_AC_2, delete_dsn = TRUE, quiet = TRUE)
```

## Corredores Biológicos

```{r}
#| label: descarga-cb
#| eval: true


# Ruta a los archivos de salida
ARCHIVO_GPKG_CB_1 <- here("datos", "finales", "corredores-biologicos.gpkg")
ARCHIVO_GPKG_CB_2 <- here("programas", "geovisor", "corredores-biologicos.gpkg")

# Direcciones WFS
WFS_BASE <- "http://geos1pne.sirefor.go.cr/wfs"
WFS_VERSION <- "1.0.0"
WFS_CAPA <- "PNE:corredoresbiologicos"

# Solicitud WFS
solicitud_wfs <- sprintf(
  "request=GetFeature&service=WFS&version=%s&typename=%s&outputFormat=application/json",
  WFS_VERSION,
  URLencode(WFS_CAPA)
)

# Carga, reproyección, validación de geometrías y unión
capa_sf <-
  st_read(paste0(URLencode(WFS_BASE), "?", solicitud_wfs), quiet = TRUE) |>
  st_transform(4326) |>
  st_make_valid()

# Escritura
capa_sf |>
  st_write(ARCHIVO_GPKG_CB_1, delete_dsn = TRUE, quiet = TRUE)
capa_sf |>
  st_write(ARCHIVO_GPKG_CB_2, delete_dsn = TRUE, quiet = TRUE)
```


## Cobertura Forestal

```{r}
#| label: descarga-cf
#| eval: false


# Ruta a los archivos de salida
ARCHIVO_GPKG_CF_1 <- here("datos", "finales", "cobertura_forestal.gpkg")
ARCHIVO_GPKG_CF_2 <- here("programas", "geovisor", "cobertura_forestal.gpkg")

# Direcciones WFS
WFS_BASE <- "http://geos1pne.sirefor.go.cr/wfs"
WFS_VERSION <- "1.0.0"
WFS_CAPA <- "PNE:cobertura_forestal_2023"

# Solicitud WFS
solicitud_wfs <- sprintf(
  "request=GetFeature&service=WFS&version=%s&typename=%s&outputFormat=application/json",
  WFS_VERSION,
  URLencode(WFS_CAPA)
)

# Carga, reproyección, validación de geometrías y unión
capa_sf <-
  st_read(paste0(URLencode(WFS_BASE), "?", solicitud_wfs), quiet = TRUE) |>
  st_transform(4326) |>
  st_make_valid()

# Escritura
capa_sf |>
  st_write(ARCHIVO_GPKG_CF_1, delete_dsn = TRUE, quiet = TRUE)
capa_sf |>
  st_write(ARCHIVO_GPKG_CF_2, delete_dsn = TRUE, quiet = TRUE)
```